package com.mirador.customer;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.IntRange;
import org.junit.jupiter.api.Test;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property-based tests for {@link AggregationService} — Phase 2.5 T3.
 *
 * <p>Complements {@code AggregationServiceTest} (the existing example-based
 * JUnit test that checks a single happy path + a single parallel wall-clock
 * assertion). Here we use jqwik to verify the SAME invariant across a range
 * of input sizes — proving parallelism holds not only for "2 tasks in
 * parallel" but for "N concurrent aggregate() invocations", which is closer
 * to the production reality where multiple requests hit the endpoint
 * simultaneously.
 *
 * <h2>Why property-based here?</h2>
 *
 * {@code AggregationService.aggregate()} itself takes no arguments — there's
 * nothing to parameterise at the method level. But the USE of the method
 * in a concurrent context has a clear invariant:
 *
 * <blockquote>
 *   For any N ∈ [1, 10], running N concurrent {@code aggregate()} calls
 *   on a virtual-thread executor must complete in wall-clock time less
 *   than a small constant (because each aggregate() itself runs its
 *   sub-tasks in parallel and takes ~200 ms of sleep, so N of them in
 *   parallel should still take ~200 ms plus scheduling overhead, not
 *   N × 200 ms).
 * </blockquote>
 *
 * jqwik generates random N values in the given range and runs the test
 * body for each — a single regression (e.g. someone accidentally makes
 * {@code loadCustomerData} synchronous with a {@code synchronized} block)
 * would fail on most N values and jqwik would report the smallest failing
 * case via shrinking.
 */
class AggregationServicePropertyTest {

    private final AggregationService service = new AggregationService();

    /**
     * Classic baseline — kept as a {@link Test} so the existing example
     * in {@code AggregationServiceTest} has an analogue here for
     * comparison readers.
     */
    @Test
    void aggregate_returnsExpectedData() {
        AggregationService.AggregatedResponse response = service.aggregate();
        assertThat(response.customerData()).isEqualTo("customer-data");
        assertThat(response.stats()).isEqualTo("stats");
    }

    /**
     * Invariant: N concurrent {@code aggregate()} calls finish in roughly
     * the latency of a SINGLE call, not N-times-that latency.
     *
     * <p>Each {@code aggregate()} sleeps ~200 ms internally (two sub-tasks
     * in parallel). Running N of them concurrently on a virtual-thread
     * executor should take ~200 ms + overhead — NOT N × 200 ms.
     *
     * <p>Upper bound chosen generously (1200 ms for N ≤ 10) to tolerate
     * runner jitter on the shared macbook-local CI runner. Same rationale
     * as the 600 ms bump in {@code AggregationServiceTest} after repeated
     * flakes at 420 ms. If this property fails with a large wall-clock,
     * virtual-thread scheduling has regressed or the sub-tasks became
     * serial — either case is a real problem.
     *
     * @param n number of concurrent aggregate() calls, generated by jqwik
     */
    @Property(tries = 20)
    void concurrent_aggregates_dont_scale_linearly(@ForAll @IntRange(min = 1, max = 10) int n) {
        long startNanos = System.nanoTime();

        try (ExecutorService exec = Executors.newVirtualThreadPerTaskExecutor()) {
            Future<?>[] futures = IntStream.range(0, n)
                    .mapToObj(i -> exec.submit(service::aggregate))
                    .toArray(Future<?>[]::new);
            // Block on all futures; the try-with-resources closes the
            // executor which implicitly joins any remaining tasks.
            for (Future<?> f : futures) {
                try {
                    f.get();
                } catch (Exception e) {
                    throw new AssertionError(
                            "aggregate() future failed for concurrency n=" + n, e);
                }
            }
        }

        long elapsedMs = (System.nanoTime() - startNanos) / 1_000_000;

        // The serial floor is n × 400 ms if parallelism were broken
        // AND each aggregate() ran its sub-tasks serially. Well-behaved:
        // ~200 ms + overhead regardless of n, bounded at 1200 ms.
        assertThat(elapsedMs)
                .as("n=%d concurrent aggregate() calls should finish fast via virtual threads",
                        n)
                .isLessThan(1200);
    }
}
