services:

  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: springapi-lgtm
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus
    volumes:
      # config
      # Prometheus deja defini
      #- ./ops/observability/grafana/provisioning/datasources/datasource-demo.yaml:/otel-lgtm/grafana/conf/provisioning/datasources/datasource-demo.yaml
      - ./ops/observability/grafana/dashboards-lgtm/dashboard-demo-lgtm.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/dashboard-demo-lgtm.yaml
      - ./ops/observability/grafana/dashboards-lgtm/demo.json:/otel-lgtm/demo.json
    environment:
      ENABLE_LOGS_ALL: "true"

  prometheus:
    image: prom/prometheus:latest
    container_name: springapi-prometheus
    command:
      # standard path
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      # reference the host ip
      - "host.docker.internal:host-gateway"
    volumes:
      # config
      - ./ops/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: springapi-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      # config
      - ./ops/observability/grafana/provisioning:/etc/grafana/provisioning
      - ./ops/observability/grafana/dashboards:/var/lib/grafana/dashboards

#  jaeger:
#    image: cr.jaegertracing.io/jaegertracing/jaeger:2.17.0
#    ports:
#      - "16686:16686"
#      - "4317:4317"
#      - "4318:4318"