package com.mirador.customer;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.IntRange;
import org.junit.jupiter.api.Test;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * J17 overlay of {@link AggregationServicePropertyTest} — replaces 2 J19/21+ APIs :
 *
 * <ul>
 *   <li>{@code Executors.newVirtualThreadPerTaskExecutor()} (J21+) →
 *       {@code Executors.newCachedThreadPool()} (platform threads, all Java versions).</li>
 *   <li>try-with-resources on {@code ExecutorService} (the ExecutorService.close()
 *       autocloseable hook is J19+) → explicit try/finally + {@code shutdown()}.</li>
 * </ul>
 *
 * <p>Functionally equivalent for the property under test : N concurrent calls of
 * {@code aggregate()} still finish in roughly the latency of a single call
 * because each {@code aggregate()} parallelises its 2 sub-tasks. Platform
 * threads are heavier (1:1 OS thread, ~1 MB stack each) than virtual threads,
 * but for N ≤ 10 the difference is irrelevant — the parallelism property still
 * holds. The 1 200 ms upper bound stays the same.
 *
 * <p>Pattern : same as the main {@link AggregationService} overlay
 * ({@code src/main/java-overlays/java17/...}) — single-source-of-truth lives in
 * {@code src/main/java/} (or {@code src/test/java/}), J17 alternative replaces
 * it for the {@code -Djava17} compat build only.
 */
class AggregationServicePropertyTest {

    private final AggregationService service = new AggregationService();

    /** Baseline kept for parity with {@code AggregationServiceTest} example. */
    @Test
    void aggregate_returnsExpectedData() {
        AggregationService.AggregatedResponse response = service.aggregate();
        assertThat(response.customerData()).isEqualTo("customer-data");
        assertThat(response.stats()).isEqualTo("stats");
    }

    /**
     * Same invariant as the J21+ variant — N concurrent aggregate() calls finish
     * in roughly single-call latency. Platform-thread executor here (J17 build).
     *
     * @param n number of concurrent aggregate() calls, generated by jqwik
     */
    @Property(tries = 20)
    void concurrent_aggregates_dont_scale_linearly(@ForAll @IntRange(min = 1, max = 10) int n) {
        long startNanos = System.nanoTime();

        ExecutorService exec = Executors.newCachedThreadPool();
        try {
            Future<?>[] futures = IntStream.range(0, n)
                    .mapToObj(i -> exec.submit(service::aggregate))
                    .toArray(Future<?>[]::new);
            // Block on all futures — equivalent to the try-with-resources
            // implicit close() in the J21+ variant which would join remaining tasks.
            for (Future<?> f : futures) {
                try {
                    f.get();
                } catch (Exception e) {
                    throw new AssertionError(
                            "aggregate() future failed for concurrency n=" + n, e);
                }
            }
        } finally {
            exec.shutdown();
        }

        long elapsedMs = (System.nanoTime() - startNanos) / 1_000_000;

        assertThat(elapsedMs)
                .as("n=%d concurrent aggregate() calls should finish fast via platform threads",
                        n)
                .isLessThan(1200);
    }
}
