package com.example.springapi.client;

import org.springframework.web.service.annotation.GetExchange;
import org.springframework.web.service.annotation.HttpExchange;

import java.util.List;

/**
 * Declarative HTTP client (Spring 6 HTTP Interface) targeting the JSONPlaceholder public API.
 *
 * <p>Annotating an interface with {@code @HttpExchange} and its methods with exchange-type
 * annotations ({@code @GetExchange}, {@code @PostExchange}, etc.) is the Spring 6 way to
 * define type-safe, testable HTTP clients without writing any implementation code.
 * The actual proxy implementation is generated by {@code HttpServiceProxyFactory} and registered
 * as a Spring bean in {@link com.example.springapi.config.HttpClientConfig}.
 *
 * <p>JSONPlaceholder ({@code https://jsonplaceholder.typicode.com}) is a free public REST API
 * that provides fake data for testing and prototyping. It is used here to demonstrate
 * outbound HTTP calls with circuit-breaker protection.
 *
 * <p>This interface is injected into {@link com.example.springapi.service.TodoService},
 * which adds Resilience4j circuit-breaker and retry on top of calls to this client.
 */
@HttpExchange(url = "https://jsonplaceholder.typicode.com")
public interface JsonPlaceholderClient {

    /**
     * Fetches the todo list for a given user ID.
     * Maps to {@code GET https://jsonplaceholder.typicode.com/users/{id}/todos}.
     */
    @GetExchange("/users/{id}/todos")
    List<TodoItem> getTodos(long id);
}
