package com.example.springapi.controller;

import com.example.springapi.security.JwtTokenProvider;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * Authentication controller — issues JWT tokens in exchange for credentials.
 *
 * <h3>Scope</h3>
 * <p>This controller demonstrates the token-issuance side of JWT authentication.
 * In a production system, credential validation would be delegated to a UserDetailsService
 * backed by a database, or to an external identity provider (Keycloak, Auth0, etc.).
 *
 * <h3>Demo credentials</h3>
 * <p>The username/password ({@code admin}/{@code admin}) are hardcoded constants for demo
 * purposes only. There is no user database, no password hashing, and no account lockout.
 * <b>Never use this approach in production.</b>
 *
 * <h3>Token issuance flow</h3>
 * <ol>
 *   <li>Client sends {@code POST /auth/login} with a JSON body: {@code {"username":"admin","password":"admin"}}</li>
 *   <li>If credentials match, a signed JWT is generated by {@link JwtTokenProvider} (24 h validity).</li>
 *   <li>The token is returned as {@code {"token": "<jwt>"}}</li>
 *   <li>The client includes the token in subsequent requests:
 *       {@code Authorization: Bearer <jwt>}</li>
 * </ol>
 *
 * <h3>LoginRequest record</h3>
 * <p>The nested {@link LoginRequest} record is defined here rather than in a separate DTO file
 * because it is only used by this controller — co-locating it avoids unnecessary file proliferation.
 */
@RestController
@RequestMapping("/auth")
public class AuthController {

    // Demo-only credentials — replace with UserDetailsService + BCrypt in production
    private static final String ADMIN_USERNAME = "admin";
    private static final String ADMIN_PASSWORD = "admin";

    private final JwtTokenProvider jwtTokenProvider;

    public AuthController(JwtTokenProvider jwtTokenProvider) {
        this.jwtTokenProvider = jwtTokenProvider;
    }

    /**
     * Validates credentials and returns a signed JWT.
     * Returns HTTP 401 with an error body if credentials are incorrect.
     * Uses {@code ResponseEntity<?>} (raw wildcard) to return different body types on success vs. failure.
     */
    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody LoginRequest request) {
        if (!ADMIN_USERNAME.equals(request.username()) || !ADMIN_PASSWORD.equals(request.password())) {
            return ResponseEntity.status(401).body(Map.of("error", "Invalid credentials"));
        }
        String token = jwtTokenProvider.generateToken(request.username());
        return ResponseEntity.ok(Map.of("token", token));
    }

    /**
     * Login request DTO — co-located with the controller since it is only used here.
     * Jackson deserializes the JSON body to this record via the canonical constructor.
     */
    public record LoginRequest(String username, String password) {}
}
