#!/usr/bin/env python3
"""Wrap Sloth's raw rules YAML as a kube-prometheus-stack PrometheusRule CRD.

Sloth's `--k8s-transform-plugin-id="sloth.dev/k8stransform/prom-operator-prometheus-rule/v1"`
flag is supposed to do this in 0.16.0 but currently emits the raw rules
without the CRD wrapper. This script bridges the gap.

Usage :
  cd <repo>/mirador-service-java
  sloth generate -i docs/slo/slo.yaml -o /tmp/mirador-slo-rules.yaml
  python3 docs/slo/wrap-as-prometheusrule.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SHARED_DIR = REPO_ROOT.parent / "mirador-service-shared"
INPUT = Path("/tmp/mirador-slo-rules.yaml")
OUTPUT = SHARED_DIR / "deploy/kubernetes/observability-prom/mirador-slo.yaml"

HEADER = """# =============================================================================
# deploy/kubernetes/observability-prom/mirador-slo.yaml
#
# SLO recording + multi-window multi-burn-rate alerting rules. Generated by
# Sloth (https://sloth.dev/) from `mirador-service-java/docs/slo/slo.yaml`,
# then wrapped as a kube-prometheus-stack PrometheusRule CRD by
# `mirador-service-java/docs/slo/wrap-as-prometheusrule.py`.
#
# DO NOT EDIT manually. Regenerate after editing the source SLO YAML :
#
#   cd <repo>/mirador-service-java
#   sloth generate -i docs/slo/slo.yaml -o /tmp/mirador-slo-rules.yaml
#   python3 docs/slo/wrap-as-prometheusrule.py
#
# Pattern : Google SRE Workbook ch. 5 — multi-window multi-burn-rate.
# 4 alerts per SLO (2 page = critical 1h+6h burn, 2 ticket = warning 1d+3d burn).
#
# Same `release: prometheus-stack` label convention as mirador-alerts.yaml so
# the kube-prometheus-stack operator picks them up. Apply via Argo CD or
# kustomize — the operator's ruleSelector grabs both files.
# =============================================================================
"""


def main() -> int:
    if not INPUT.exists():
        print(f"ERROR: {INPUT} not found. Run `sloth generate` first.", file=sys.stderr)
        return 1

    with INPUT.open() as f:
        sloth = yaml.safe_load(f)

    prom_rule = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "mirador-slo",
            "labels": {
                "release": "prometheus-stack",
                "role": "alert-rules",
                "app.kubernetes.io/part-of": "mirador",
            },
        },
        "spec": {
            "groups": sloth["groups"],
        },
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w") as f:
        f.write(HEADER)
        yaml.safe_dump(
            prom_rule,
            f,
            default_flow_style=False,
            sort_keys=False,
            width=120,
        )

    total_records = sum(len([r for r in g["rules"] if "record" in r]) for g in sloth["groups"])
    total_alerts = sum(len([r for r in g["rules"] if "alert" in r]) for g in sloth["groups"])
    print(f"Wrote {OUTPUT}")
    print(f"  groups: {len(sloth['groups'])}")
    print(f"  recording rules: {total_records}")
    print(f"  alert rules: {total_alerts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
